### ISSUE TITLE
Austria missing as a country

### ISSUE THREAD

**Issue by tstdcmd** [kapilkumar0037/ngx-countries-dropdown#17]
Hey there. 
I think Austria is missing as a country in the dropdown. Is it possible to add austria to it? 

Austria (Österreich)
The dial is +43.

Greetings.

**Comment by kapilkumar0037** [comment]
Hi, Thanks for reporting. Will add and let you know once done.

**Comment by tstdcmd** [comment]
![image](https://github.com/user-attachments/assets/9cbdd260-a99e-4999-96d6-3fd62a2f8f70)
Thank you, works fine!
