### ISSUE TITLE
after hiding dial code  [countryListConfig] = "countryListConfig" in the list it is getting hided but not when value is selected

### ISSUE THREAD

**Issue by kotte94** [kapilkumar0037/ngx-countries-dropdown#19]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kotte94** [comment]
version  number 1.051

**Comment by kapilkumar0037** [comment]
Hi @kotte94, 
you need to set the **selectedCountryConfig** as well to hide the same from selected country. 
Thanks, 
Kapil
