### ISSUE TITLE
i need select country with dialcode

### ISSUE THREAD

**Issue by Abdullah-Bataineh** [kapilkumar0037/ngx-countries-dropdown#21]
i need select country with dialcode such ass with phone number is +972xxxxxx with update i need +972 in selectcountry with show country

**Comment by kapilkumar0037** [comment]
isn't it already there https://kapilkumar0037.github.io/ngx-countries-dropdown-demo/#/dialcode?
If it is not what you need please explain a bit more your requirement

**Comment by Abdullah-Bataineh** [comment]
> isn't it already there https://kapilkumar0037.github.io/ngx-countries-dropdown-demo/#/dialcode?
> 
> If it is not what you need please explain a bit more your requirement

Ok , with in tag selector <ngx-select-country>
[selectcountry]="'JO'"
</ngx-select-country>

I need in this [selectcountry]="'JO'" i need  set +962 with show jordan for example , I don't know if this example exists originally, so I'm looking for this thing.

**Comment by kapilkumar0037** [comment]
it's already there. just have a look at the documentation. to select a default country use "selectedCountryCode" .
[selectedCountryCode]="'JO'"
