### ISSUE TITLE
Put the search box in place of the dropdown button

### ISSUE THREAD

**Issue by AmrElsayyad** [kapilkumar0037/ngx-countries-dropdown#9]
**Is your feature request related to a problem? Please describe.**
Having the search box as a list item makes it harder to use.

**Describe the solution you'd like**
It would be better if the dropdown button acted as the search box instead of having it as a list item.

**Describe alternatives you've considered**
None

**Additional context**
![image](https://github.com/kapilkumar0037/ngx-countries-dropdown/assets/20210190/27fa0380-49f2-4bd6-9179-f7e619d8198c)

**Comment by kapilkumar0037** [comment]
Thanks for your suggestion, it has been implemented and included in the release 2.0.3.
https://kapilkumar0037.github.io/ngx-countries-dropdown-demo

**Comment by AmrElsayyad** [comment]
Thank you @kapilkumar0037 !!
It would be perfect, if you also implement selecting the first option on enter key press.

**Comment by kapilkumar0037** [comment]
Implemented that as well. you can now navigate through the list with up and down arrow and select with enter key.

**Comment by AmrElsayyad** [comment]
@kapilkumar0037 Thank you!!
